version: '3.9'
services:
  houlala-web:
    image: pierreedimo777/houlala-frontend
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/app/
      # Just specify a path and let the Engine create a volume
      - /app/node_modules/


